## Week 1: Data Understanding & Preprocessing
### Task 1 : Setup & GitHub Integration

In [1]:
import pandas as pd
import numpy as np

##### Importing CSV and display 5 rows(default)

In [2]:
df = pd.read_csv('Dataset/Amazon Sale Report.csv')
df.head()

/var/folders/n6/rdkdg7zn25j638bgsp4jznjc0000gp/T/ipykernel_19962/401294409.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Dataset/Amazon Sale Report.csv')

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

## Task 2 : Data Cleaning & Preprocessing

#### 1. Basic Description of the dataset

In [3]:
df.info()
df.describe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

<bound method NDFrame.describe of          index             Order ID      Date                        Status  \
0            0  405-8078784-5731545  04-30-22                     Cancelled
1            1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2            2  404-0687676-7273146  04-30-22                       Shipped
3            3  403-9615377-8133951  04-30-22                     Cancelled
4            4  407-1069790-7240320  04-30-22                       Shipped
...        ...                  ...       ...                           ...
128970  128970  406-6001380-7673107  05-31-22                       Shipped
128971  128971  402-9551604-7544318  05-31-22                       Shipped
128972  128972  407-9547469-3152358  05-31-22                       Shipped
128973  128973  402-6184140-0545956  05-31-22                       Shipped
128974  128974  408-7436540-8728312  05-31-22                       Shipped

       Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0        Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1        Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2          Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3        Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4          Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL
...           ...            ...                ...      ...              ...
128970     Amazon      Amazon.in          Expedited  JNE3697    JNE3697-KR-XL
128971     Amazon      Amazon.in          Expedited   SET401   SET401-KR-NP-M
128972     Amazon      Amazon.in          Expedited    J0157     J0157-DR-XXL
128973     Amazon      Amazon.in          Expedited    J0012     J0012-SKD-XS
128974     Amazon      Amazon.in          Expedited    J0003      J0003-SET-S

             Category  ... currency   Amount    ship-city    ship-state  \
0                 Set  ...      INR   647.62       MUMBAI   MAHARASHTRA
1               kurta  ...      INR   406.00    BENGALURU     KARNATAKA
2               kurta  ...      INR   329.00  NAVI MUMBAI   MAHARASHTRA
3       Western Dress  ...      INR   753.33   PUDUCHERRY    PUDUCHERRY
4                 Top  ...      INR   574.00      CHENNAI    TAMIL NADU
...               ...  ...      ...      ...          ...           ...
128970          kurta  ...      INR   517.00    HYDERABAD     TELANGANA
128971            Set  ...      INR   999.00     GURUGRAM       HARYANA
128972  Western Dress  ...      INR   690.00    HYDERABAD     TELANGANA
128973            Set  ...      INR  1199.00        Halol       Gujarat
128974            Set  ...      INR   696.00       Raipur  CHHATTISGARH

       ship-postal-code  ship-country  \
0              400081.0            IN
1              560085.0            IN
2              410210.0            IN
3              605008.0            IN
4              600073.0            IN
...                 ...           ...
128970         500013.0            IN
128971         122004.0            IN
128972         500049.0            IN
128973         389350.0            IN
128974         492014.0            IN

                                            promotion-ids    B2B  \
0                                                     NaN  False
1       Amazon PLCC Free-Financing Universal Merchant ...  False
2            IN Core Free Shipping 2015/04/08 23-48-5-108   True
3                                                     NaN  False
4                                                     NaN  False
...                                                   ...    ...
128970                                                NaN  False
128971       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128972                                                NaN  False
128973       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128974       IN Core Free Shipping 2015/04/08 23-48-5-108  False

        fulfilled-by Unnamed: 22
0          Easy Ship         NaN
1          Easy Ship         NaN
2                NaN         NaN
3          Easy Ship         NaN
4                NaN         NaN
...              ...         ...
128970           NaN       False
128971           NaN       False
128972           NaN       False
128973           NaN       False
128974           NaN       False

[128975 rows x 24 columns]>

#### 2a. Identify and Display in every column how many Missing Values are present

In [4]:
df.isnull().any()

index                 False
Order ID              False
Date                  False
Status                False
Fulfilment            False
Sales Channel         False
ship-service-level    False
Style                 False
SKU                   False
Category              False
Size                  False
ASIN                  False
Courier Status         True
Qty                   False
currency               True
Amount                 True
ship-city              True
ship-state             True
ship-postal-code       True
ship-country           True
promotion-ids          True
B2B                   False
fulfilled-by           True
Unnamed: 22            True
dtype: bool

In [5]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

#### 2b. Check for duplicate rows and Count them

In [6]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
128970    False
128971    False
128972    False
128973    False
128974    False
Length: 128975, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [index, Order ID, Date, Status, Fulfilment, Sales Channel , ship-service-level, Style, SKU, Category, Size, ASIN, Courier Status, Qty, currency, Amount, ship-city, ship-state, ship-postal-code, ship-country, promotion-ids, B2B, fulfilled-by, Unnamed: 22]
Index: []

[0 rows x 24 columns]

#### 2c. Finding the inconsistencies :

Printing all the column names

In [9]:
for col in df.columns:
    print(col)

index
Order ID
Date
Status
Fulfilment
Sales Channel
ship-service-level
Style
SKU
Category
Size
ASIN
Courier Status
Qty
currency
Amount
ship-city
ship-state
ship-postal-code
ship-country
promotion-ids
B2B
fulfilled-by
Unnamed: 22

#### Printing all the unique values of all the columns

In [10]:
for col in df.columns:
    print(f"\n{col}:")
    print(df[col].unique())

index:
[     0      1      2 ... 128972 128973 128974]

Order ID:
['405-8078784-5731545' '171-9198151-1101146' '404-0687676-7273146' ...
 '407-9547469-3152358' '402-6184140-0545956' '408-7436540-8728312']

Date:
['04-30-22' '04-29-22' '04-28-22' '04-27-22' '04-26-22' '04-25-22'
 '04-24-22' '04-23-22' '04-22-22' '04-21-22' '04-20-22' '04-19-22'
 '04-18-22' '04-17-22' '04-16-22' '04-15-22' '04-14-22' '04-13-22'
 '04-12-22' '04-11-22' '04-10-22' '04-09-22' '04-08-22' '04-07-22'
 '04-06-22' '04-05-22' '04-04-22' '04-03-22' '04-02-22' '04-01-22'
 '03-31-22' '05-31-22' '05-30-22' '05-29-22' '05-28-22' '05-27-22'
 '05-26-22' '05-25-22' '05-24-22' '05-23-22' '05-22-22' '05-21-22'
 '05-20-22' '05-19-22' '05-18-22' '05-17-22' '05-16-22' '05-15-22'
 '05-14-22' '05-13-22' '05-12-22' '05-11-22' '05-10-22' '05-09-22'
 '05-08-22' '05-07-22' '05-06-22' '05-05-22' '05-04-22' '05-03-22'
 '05-02-22' '05-01-22' '06-29-22' '06-28-22' '06-27-22' '06-26-22'
 '06-25-22' '06-24-22' '06-23-22' '06-22-22' '06-21-22' '06-20-22'
 '06-19-22' '06-18-22' '06-17-22' '06-16-22' '06-15-22' '06-14-22'
 '06-13-22' '06-12-22' '06-11-22' '06-10-22' '06-09-22' '06-08-22'
 '06-07-22' '06-06-22' '06-05-22' '06-04-22' '06-03-22' '06-02-22'
 '06-01-22']

Status:
['Cancelled' 'Shipped - Delivered to Buyer' 'Shipped'
 'Shipped - Returned to Seller' 'Shipped - Rejected by Buyer'
 'Shipped - Lost in Transit' 'Shipped - Out for Delivery'
 'Shipped - Returning to Seller' 'Shipped - Picked Up' 'Pending'
 'Pending - Waiting for Pick Up' 'Shipped - Damaged' 'Shipping']

Fulfilment:
['Merchant' 'Amazon']

Sales Channel :
['Amazon.in' 'Non-Amazon']

ship-service-level:
['Standard' 'Expedited']

Style:
['SET389' 'JNE3781' 'JNE3371' ... 'SET066' 'J0286' 'SET045']

SKU:
['SET389-KR-NP-S' 'JNE3781-KR-XXXL' 'JNE3371-KR-XL' ... 'JNE3370-KR-S'
 'JNE3678-TU-XXL' 'SET045-KR-NP-M']

Category:
['Set' 'kurta' 'Western Dress' 'Top' 'Ethnic Dress' 'Bottom' 'Saree'
 'Blouse' 'Dupatta']

Size:
['S' '3XL' 'XL' 'L' 'XXL' 'XS' '6XL' 'M' '4XL' '5XL' 'Free']

ASIN:
['B09KXVBD7Z' 'B09K3WFS32' 'B07WV4JV4D' ... 'B081X6MVKK' 'B0943HSR64'
 'B07N81TFNY']

Courier Status:
[nan 'Shipped' 'Cancelled' 'Unshipped']

Qty:
[ 0  1  2 15  3  9 13  5  4  8]

currency:
['INR' nan]

Amount:
[ 647.62  406.    329.   ...  708.58 1244.    639.  ]

ship-city:
['MUMBAI' 'BENGALURU' 'NAVI MUMBAI' ... 'GULABPURA, Distt BHILWARA'
 'Prayagraj (ALLAHABAD)' 'Halol']

ship-state:
['MAHARASHTRA' 'KARNATAKA' 'PUDUCHERRY' 'TAMIL NADU' 'UTTAR PRADESH'
 'CHANDIGARH' 'TELANGANA' 'ANDHRA PRADESH' 'RAJASTHAN' 'DELHI' 'HARYANA'
 'ASSAM' 'JHARKHAND' 'CHHATTISGARH' 'ODISHA' 'KERALA' 'MADHYA PRADESH'
 'WEST BENGAL' 'NAGALAND' 'Gujarat' 'UTTARAKHAND' 'BIHAR'
 'JAMMU & KASHMIR' 'PUNJAB' 'HIMACHAL PRADESH' 'ARUNACHAL PRADESH'
 'MANIPUR' 'Goa' 'MEGHALAYA' 'GOA' 'TRIPURA' 'LADAKH' 'DADRA AND NAGAR'
 'SIKKIM' 'Delhi' nan 'ANDAMAN & NICOBAR ' 'Punjab' 'Rajshthan' 'Manipur'
 'rajasthan' 'Odisha' 'NL' 'Bihar' 'MIZORAM' 'punjab' 'New Delhi'
 'Rajasthan' 'Punjab/Mohali/Zirakpur' 'Puducherry' 'delhi' 'RJ'
 'Chandigarh' 'orissa' 'LAKSHADWEEP' 'goa' 'PB' 'APO' 'Arunachal Pradesh'
 'AR' 'Pondicherry' 'Sikkim' 'Arunachal pradesh' 'Nagaland' 'bihar'
 'Mizoram' 'rajsthan' 'Orissa' 'Rajsthan' 'Meghalaya']

ship-postal-code:
[400081. 560085. 410210. ... 609603. 851205. 629152.]

ship-country:
['IN' nan]

promotion-ids:
[nan
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-CXNSLNBROFDW4,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-WSJLDN3X7KEMO,Amazon PLCC Free-Financing Universal Merchant AAT-VL6FGQVGQVXUS,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-XVPICCHRWDCAI,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'IN Core Free Shipping 2015/04/08 23-48-5-108' ...
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292']

B2B:
[False  True]

fulfilled-by:
['Easy Ship' nan]

Unnamed: 22:
[nan False]

#### Inconsistency in the state names :

In [11]:
df['ship-state'].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'Gujarat', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'Goa', 'MEGHALAYA', 'GOA',
       'TRIPURA', 'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'Delhi', nan,
       'ANDAMAN & NICOBAR ', 'Punjab', 'Rajshthan', 'Manipur',
       'rajasthan', 'Odisha', 'NL', 'Bihar', 'MIZORAM', 'punjab',
       'New Delhi', 'Rajasthan', 'Punjab/Mohali/Zirakpur', 'Puducherry',
       'delhi', 'RJ', 'Chandigarh', 'orissa', 'LAKSHADWEEP', 'goa', 'PB',
       'APO', 'Arunachal Pradesh', 'AR', 'Pondicherry', 'Sikkim',
       'Arunachal pradesh', 'Nagaland', 'bihar', 'Mizoram', 'rajsthan',
       'Orissa', 'Rajsthan', 'Meghalaya'], dtype=object)

#### State names (all lower case) value counts

In [12]:
df['ship-state'].str.lower().value_counts()

ship-state
maharashtra               22260
karnataka                 17326
tamil nadu                11483
telangana                 11330
uttar pradesh             10638
delhi                      6967
kerala                     6585
west bengal                5963
andhra pradesh             5430
gujarat                    4489
haryana                    4415
rajasthan                  2711
madhya pradesh             2529
odisha                     2136
bihar                      2114
punjab                     1917
assam                      1663
uttarakhand                1553
jharkhand                  1456
goa                        1137
chhattisgarh                909
himachal pradesh            788
jammu & kashmir             702
puducherry                  350
chandigarh                  333
manipur                     316
andaman & nicobar           257
meghalaya                   207
sikkim                      205
nagaland                    185
tripura                     151
arunachal pradesh           146
new delhi                    81
mizoram                      76
dadra and nagar              70
ladakh                       43
lakshadweep                   4
rajshthan                     3
orissa                        3
nl                            2
rj                            2
rajsthan                      2
punjab/mohali/zirakpur        1
pb                            1
apo                           1
ar                            1
pondicherry                   1
Name: count, dtype: int64

#### City names (all lower case) value counts

In [13]:
df['ship-city'].str.lower().value_counts()

ship-city
bengaluru                11898
hyderabad                 9125
mumbai                    7122
new delhi                 6340
chennai                   6284
                         ...
kim                          1
edapally north po            1
mandi gobindgarh             1
cherupuzha                   1
prayagraj (allahabad)        1
Name: count, Length: 7297, dtype: int64

#### state-name column inconsistencies : 
1. Names of state are repeated (lowercase, uppercase).
2. After making every names into lowercase and finding the sum, we found that there are some state names given in the SHORTFORMS which again makes it inconsistent.

#### state-city column inconsistencies : 
1. Some entries have bracketed alternate names.

#### 3. Handling missing values :

#### 3a. Removal of unnecessary columns :

#### Columns: 
<br>'Unnamed: 22' : Has no correlation with any of the columns, so removed
<br>'ship-country' : It is India's data, so this column is of no use.
<br>'index' : Basic indexing of the rows, so it is removed.
<br>columns are of no use, so they are being dropped.

In [14]:

newdf = df.drop(columns=['Unnamed: 22', 'ship-country','index'])

#### Finding the percentage of nulls present in every column (descending order)

In [15]:
(newdf.isna().mean() * 100).sort_values(ascending=False)

fulfilled-by          69.546811
promotion-ids         38.110487
Amount                 6.043807
currency               6.043807
Courier Status         5.328164
ship-postal-code       0.025586
ship-state             0.025586
ship-city              0.025586
B2B                    0.000000
Qty                    0.000000
Order ID               0.000000
Date                   0.000000
Size                   0.000000
Category               0.000000
SKU                    0.000000
Style                  0.000000
ship-service-level     0.000000
Sales Channel          0.000000
Fulfilment             0.000000
Status                 0.000000
ASIN                   0.000000
dtype: float64

#### Column : 'fulfilled-by' has 69% of null values which is why I dropped that column, and it only has one other value.

In [16]:
newdf=newdf.drop(columns=['fulfilled-by'])

In [17]:
#Storing if needed in future reference
fulfilled_df=df['fulfilled-by']

#### 3b. Missing values checking :

In [18]:
(newdf.isna().mean() * 100).sort_values(ascending=False)

promotion-ids         38.110487
Amount                 6.043807
currency               6.043807
Courier Status         5.328164
ship-postal-code       0.025586
ship-state             0.025586
ship-city              0.025586
Order ID               0.000000
Date                   0.000000
Qty                    0.000000
ASIN                   0.000000
Size                   0.000000
Category               0.000000
SKU                    0.000000
Style                  0.000000
ship-service-level     0.000000
Sales Channel          0.000000
Fulfilment             0.000000
Status                 0.000000
B2B                    0.000000
dtype: float64

#### Column 'Amount' null values can be filled with '0.00'.

In [19]:
newdf[newdf['Amount'].isna()]

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,promotion-ids,B2B
8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,B08L91ZZXN,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
29,404-5933402-8801952,04-30-22,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,B07JG3CND8,NaN,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,NaN,False
65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,XXL,B082W8RWN1,Cancelled,0,NaN,NaN,Dahod,Gujarat,389151.0,NaN,False
84,403-9950518-0349133,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,M,B08WPR5MCB,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500072.0,NaN,False
95,405-9112089-3379536,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,L,B081WSCKPQ,Cancelled,0,NaN,NaN,PUNE,MAHARASHTRA,411046.0,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128903,406-3923120-4345139,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3801,JNE3801-KR-M,kurta,M,B09SDZ4FH9,Cancelled,0,NaN,NaN,ANANTAPUR,ANDHRA PRADESH,515001.0,NaN,False
128907,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW014,NW014-ST-SR-XXXL,Set,3XL,B0928ZT74Y,Cancelled,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,NaN,False
128908,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW007,NW007-ST-CP-XXXL,Set,3XL,B0928YCMQP,Cancelled,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,NaN,False
128958,408-9513596-4393945,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,SET058,SET058-KR-NP-L,Set,L,B07R487XRD,Cancelled,0,NaN,NaN,Bengaluru,KARNATAKA,560037.0,NaN,False
128967,404-5182288-1653947,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,XS,B09814Q3QH,Cancelled,0,NaN,NaN,Kolkata,WEST BENGAL,700040.0,NaN,False

In [20]:
newdf['Amount']=df['Amount'].fillna(0.00)

#### Column 'currency' will be 'INR' throughout, so filled all the nans.

In [21]:
newdf['currency']=df['currency'].fillna('INR')

In [22]:
(newdf.isna().mean() * 100).sort_values(ascending=False)

promotion-ids         38.110487
Courier Status         5.328164
ship-postal-code       0.025586
ship-state             0.025586
ship-city              0.025586
Order ID               0.000000
Date                   0.000000
Amount                 0.000000
currency               0.000000
Qty                    0.000000
ASIN                   0.000000
Size                   0.000000
Category               0.000000
SKU                    0.000000
Style                  0.000000
ship-service-level     0.000000
Sales Channel          0.000000
Fulfilment             0.000000
Status                 0.000000
B2B                    0.000000
dtype: float64

#### Column 'currency' has no significance as it is 'INR' throughout, so it is dropped.

In [23]:
newdf=newdf.drop(columns=['currency'])

#### Column 'promotion-ids' has a lot of nan, but it might be useful in the future reference, so we will store it in another df and dropped in the current df.

In [24]:
promotionid_df=newdf['promotion-ids']

In [25]:
newdf=newdf.drop(columns=['promotion-ids'])

#### Column 'Courier Status' has 5.32% nuls, to handle that, we are going to check the rows where 'Courier Status' is null and 'Status' column has values 'Cancelled', we will make those nuls change into 'Cancelled'. The rest ones were labeled 'Shipped' because they were either delivered and not picked or delivered and returned, so shipping is possible.

In [26]:
newdf.loc[(newdf['Courier Status'].isna()) & (newdf['Status']=='Cancelled'),'Courier Status']='Cancelled'

In [27]:
newdf['Courier Status']=newdf['Courier Status'].fillna('Shipped')

#### Finding the percentage of nulls present in every column (descending order)

In [28]:
(newdf.isna().mean() * 100).sort_values(ascending=False)

ship-postal-code      0.025586
ship-state            0.025586
ship-city             0.025586
Order ID              0.000000
Date                  0.000000
Amount                0.000000
Qty                   0.000000
Courier Status        0.000000
ASIN                  0.000000
Size                  0.000000
Category              0.000000
SKU                   0.000000
Style                 0.000000
ship-service-level    0.000000
Sales Channel         0.000000
Fulfilment            0.000000
Status                0.000000
B2B                   0.000000
dtype: float64

#### 4. Converted date fields to proper datetime format.

In [29]:
df['Date'].dropna().unique()

array(['04-30-22', '04-29-22', '04-28-22', '04-27-22', '04-26-22',
       '04-25-22', '04-24-22', '04-23-22', '04-22-22', '04-21-22',
       '04-20-22', '04-19-22', '04-18-22', '04-17-22', '04-16-22',
       '04-15-22', '04-14-22', '04-13-22', '04-12-22', '04-11-22',
       '04-10-22', '04-09-22', '04-08-22', '04-07-22', '04-06-22',
       '04-05-22', '04-04-22', '04-03-22', '04-02-22', '04-01-22',
       '03-31-22', '05-31-22', '05-30-22', '05-29-22', '05-28-22',
       '05-27-22', '05-26-22', '05-25-22', '05-24-22', '05-23-22',
       '05-22-22', '05-21-22', '05-20-22', '05-19-22', '05-18-22',
       '05-17-22', '05-16-22', '05-15-22', '05-14-22', '05-13-22',
       '05-12-22', '05-11-22', '05-10-22', '05-09-22', '05-08-22',
       '05-07-22', '05-06-22', '05-05-22', '05-04-22', '05-03-22',
       '05-02-22', '05-01-22', '06-29-22', '06-28-22', '06-27-22',
       '06-26-22', '06-25-22', '06-24-22', '06-23-22', '06-22-22',
       '06-21-22', '06-20-22', '06-19-22', '06-18-22', '06-17-22',
       '06-16-22', '06-15-22', '06-14-22', '06-13-22', '06-12-22',
       '06-11-22', '06-10-22', '06-09-22', '06-08-22', '06-07-22',
       '06-06-22', '06-05-22', '06-04-22', '06-03-22', '06-02-22',
       '06-01-22'], dtype=object)

In [30]:
newdf['Date']=pd.to_datetime(df['Date'],format='%m-%d-%y',errors='coerce')

In [31]:
newdf['Date'].unique()

<DatetimeArray>
['2022-04-30 00:00:00', '2022-04-29 00:00:00', '2022-04-28 00:00:00',
 '2022-04-27 00:00:00', '2022-04-26 00:00:00', '2022-04-25 00:00:00',
 '2022-04-24 00:00:00', '2022-04-23 00:00:00', '2022-04-22 00:00:00',
 '2022-04-21 00:00:00', '2022-04-20 00:00:00', '2022-04-19 00:00:00',
 '2022-04-18 00:00:00', '2022-04-17 00:00:00', '2022-04-16 00:00:00',
 '2022-04-15 00:00:00', '2022-04-14 00:00:00', '2022-04-13 00:00:00',
 '2022-04-12 00:00:00', '2022-04-11 00:00:00', '2022-04-10 00:00:00',
 '2022-04-09 00:00:00', '2022-04-08 00:00:00', '2022-04-07 00:00:00',
 '2022-04-06 00:00:00', '2022-04-05 00:00:00', '2022-04-04 00:00:00',
 '2022-04-03 00:00:00', '2022-04-02 00:00:00', '2022-04-01 00:00:00',
 '2022-03-31 00:00:00', '2022-05-31 00:00:00', '2022-05-30 00:00:00',
 '2022-05-29 00:00:00', '2022-05-28 00:00:00', '2022-05-27 00:00:00',
 '2022-05-26 00:00:00', '2022-05-25 00:00:00', '2022-05-24 00:00:00',
 '2022-05-23 00:00:00', '2022-05-22 00:00:00', '2022-05-21 00:00:00',
 '2022-05-20 00:00:00', '2022-05-19 00:00:00', '2022-05-18 00:00:00',
 '2022-05-17 00:00:00', '2022-05-16 00:00:00', '2022-05-15 00:00:00',
 '2022-05-14 00:00:00', '2022-05-13 00:00:00', '2022-05-12 00:00:00',
 '2022-05-11 00:00:00', '2022-05-10 00:00:00', '2022-05-09 00:00:00',
 '2022-05-08 00:00:00', '2022-05-07 00:00:00', '2022-05-06 00:00:00',
 '2022-05-05 00:00:00', '2022-05-04 00:00:00', '2022-05-03 00:00:00',
 '2022-05-02 00:00:00', '2022-05-01 00:00:00', '2022-06-29 00:00:00',
 '2022-06-28 00:00:00', '2022-06-27 00:00:00', '2022-06-26 00:00:00',
 '2022-06-25 00:00:00', '2022-06-24 00:00:00', '2022-06-23 00:00:00',
 '2022-06-22 00:00:00', '2022-06-21 00:00:00', '2022-06-20 00:00:00',
 '2022-06-19 00:00:00', '2022-06-18 00:00:00', '2022-06-17 00:00:00',
 '2022-06-16 00:00:00', '2022-06-15 00:00:00', '2022-06-14 00:00:00',
 '2022-06-13 00:00:00', '2022-06-12 00:00:00', '2022-06-11 00:00:00',
 '2022-06-10 00:00:00', '2022-06-09 00:00:00', '2022-06-08 00:00:00',
 '2022-06-07 00:00:00', '2022-06-06 00:00:00', '2022-06-05 00:00:00',
 '2022-06-04 00:00:00', '2022-06-03 00:00:00', '2022-06-02 00:00:00',
 '2022-06-01 00:00:00']
Length: 91, dtype: datetime64[ns]

#### 5. Standardize categorical variables

In [32]:
newdf.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'Amount', 'ship-city', 'ship-state',
       'ship-postal-code', 'B2B'],
      dtype='object')

In [33]:
for col in newdf.columns:
    print(f"\n{col}:")
    print(newdf[col].unique())

Order ID:
['405-8078784-5731545' '171-9198151-1101146' '404-0687676-7273146' ...
 '407-9547469-3152358' '402-6184140-0545956' '408-7436540-8728312']

Date:
<DatetimeArray>
['2022-04-30 00:00:00', '2022-04-29 00:00:00', '2022-04-28 00:00:00',
 '2022-04-27 00:00:00', '2022-04-26 00:00:00', '2022-04-25 00:00:00',
 '2022-04-24 00:00:00', '2022-04-23 00:00:00', '2022-04-22 00:00:00',
 '2022-04-21 00:00:00', '2022-04-20 00:00:00', '2022-04-19 00:00:00',
 '2022-04-18 00:00:00', '2022-04-17 00:00:00', '2022-04-16 00:00:00',
 '2022-04-15 00:00:00', '2022-04-14 00:00:00', '2022-04-13 00:00:00',
 '2022-04-12 00:00:00', '2022-04-11 00:00:00', '2022-04-10 00:00:00',
 '2022-04-09 00:00:00', '2022-04-08 00:00:00', '2022-04-07 00:00:00',
 '2022-04-06 00:00:00', '2022-04-05 00:00:00', '2022-04-04 00:00:00',
 '2022-04-03 00:00:00', '2022-04-02 00:00:00', '2022-04-01 00:00:00',
 '2022-03-31 00:00:00', '2022-05-31 00:00:00', '2022-05-30 00:00:00',
 '2022-05-29 00:00:00', '2022-05-28 00:00:00', '2022-05-27 00:00:00',
 '2022-05-26 00:00:00', '2022-05-25 00:00:00', '2022-05-24 00:00:00',
 '2022-05-23 00:00:00', '2022-05-22 00:00:00', '2022-05-21 00:00:00',
 '2022-05-20 00:00:00', '2022-05-19 00:00:00', '2022-05-18 00:00:00',
 '2022-05-17 00:00:00', '2022-05-16 00:00:00', '2022-05-15 00:00:00',
 '2022-05-14 00:00:00', '2022-05-13 00:00:00', '2022-05-12 00:00:00',
 '2022-05-11 00:00:00', '2022-05-10 00:00:00', '2022-05-09 00:00:00',
 '2022-05-08 00:00:00', '2022-05-07 00:00:00', '2022-05-06 00:00:00',
 '2022-05-05 00:00:00', '2022-05-04 00:00:00', '2022-05-03 00:00:00',
 '2022-05-02 00:00:00', '2022-05-01 00:00:00', '2022-06-29 00:00:00',
 '2022-06-28 00:00:00', '2022-06-27 00:00:00', '2022-06-26 00:00:00',
 '2022-06-25 00:00:00', '2022-06-24 00:00:00', '2022-06-23 00:00:00',
 '2022-06-22 00:00:00', '2022-06-21 00:00:00', '2022-06-20 00:00:00',
 '2022-06-19 00:00:00', '2022-06-18 00:00:00', '2022-06-17 00:00:00',
 '2022-06-16 00:00:00', '2022-06-15 00:00:00', '2022-06-14 00:00:00',
 '2022-06-13 00:00:00', '2022-06-12 00:00:00', '2022-06-11 00:00:00',
 '2022-06-10 00:00:00', '2022-06-09 00:00:00', '2022-06-08 00:00:00',
 '2022-06-07 00:00:00', '2022-06-06 00:00:00', '2022-06-05 00:00:00',
 '2022-06-04 00:00:00', '2022-06-03 00:00:00', '2022-06-02 00:00:00',
 '2022-06-01 00:00:00']
Length: 91, dtype: datetime64[ns]

Status:
['Cancelled' 'Shipped - Delivered to Buyer' 'Shipped'
 'Shipped - Returned to Seller' 'Shipped - Rejected by Buyer'
 'Shipped - Lost in Transit' 'Shipped - Out for Delivery'
 'Shipped - Returning to Seller' 'Shipped - Picked Up' 'Pending'
 'Pending - Waiting for Pick Up' 'Shipped - Damaged' 'Shipping']

Fulfilment:
['Merchant' 'Amazon']

Sales Channel :
['Amazon.in' 'Non-Amazon']

ship-service-level:
['Standard' 'Expedited']

Style:
['SET389' 'JNE3781' 'JNE3371' ... 'SET066' 'J0286' 'SET045']

SKU:
['SET389-KR-NP-S' 'JNE3781-KR-XXXL' 'JNE3371-KR-XL' ... 'JNE3370-KR-S'
 'JNE3678-TU-XXL' 'SET045-KR-NP-M']

Category:
['Set' 'kurta' 'Western Dress' 'Top' 'Ethnic Dress' 'Bottom' 'Saree'
 'Blouse' 'Dupatta']

Size:
['S' '3XL' 'XL' 'L' 'XXL' 'XS' '6XL' 'M' '4XL' '5XL' 'Free']

ASIN:
['B09KXVBD7Z' 'B09K3WFS32' 'B07WV4JV4D' ... 'B081X6MVKK' 'B0943HSR64'
 'B07N81TFNY']

Courier Status:
['Cancelled' 'Shipped' 'Unshipped']

Qty:
[ 0  1  2 15  3  9 13  5  4  8]

Amount:
[ 647.62  406.    329.   ...  708.58 1244.    639.  ]

ship-city:
['MUMBAI' 'BENGALURU' 'NAVI MUMBAI' ... 'GULABPURA, Distt BHILWARA'
 'Prayagraj (ALLAHABAD)' 'Halol']

ship-state:
['MAHARASHTRA' 'KARNATAKA' 'PUDUCHERRY' 'TAMIL NADU' 'UTTAR PRADESH'
 'CHANDIGARH' 'TELANGANA' 'ANDHRA PRADESH' 'RAJASTHAN' 'DELHI' 'HARYANA'
 'ASSAM' 'JHARKHAND' 'CHHATTISGARH' 'ODISHA' 'KERALA' 'MADHYA PRADESH'
 'WEST BENGAL' 'NAGALAND' 'Gujarat' 'UTTARAKHAND' 'BIHAR'
 'JAMMU & KASHMIR' 'PUNJAB' 'HIMACHAL PRADESH' 'ARUNACHAL PRADESH'
 'MANIPUR' 'Goa' 'MEGHALAYA' 'GOA' 'TRIPURA' 'LADAKH' 'DADRA AND NAGAR'
 'SIKKIM' 'Delhi' nan 'ANDAMAN & NICOBAR ' 'Punjab' 'Rajshthan' 'Manipur'
 'rajasthan' 'Odisha' 'NL' 'Bihar' 'MIZORAM' 'punjab' 'New Delhi'
 'Rajasthan' 'Punjab/Mohali/Zirakpur' 'Puducherry' 'delhi' 'RJ'
 'Chandigarh' 'orissa' 'LAKSHADWEEP' 'goa' 'PB' 'APO' 'Arunachal Pradesh'
 'AR' 'Pondicherry' 'Sikkim' 'Arunachal pradesh' 'Nagaland' 'bihar'
 'Mizoram' 'rajsthan' 'Orissa' 'Rajsthan' 'Meghalaya']

ship-postal-code:
[400081. 560085. 410210. ... 609603. 851205. 629152.]

B2B:
[False  True]

#### Column 'Fulfilment','ship-service-level','Courier Status','Sales Channel '   values will be lowercased

In [34]:
newdf['Fulfilment']=newdf['Fulfilment'].str.lower()
newdf['ship-service-level']=newdf['ship-service-level'].str.lower()
newdf['Courier Status']=newdf['Courier Status'].str.lower()
newdf['Sales Channel ']=newdf['Sales Channel '].str.lower()

#### Removal of " Dress" from the 'Category' column

In [35]:
newdf['Category']=newdf['Category'].str.replace(' Dress','',regex=False)
newdf['Category']=newdf['Category'].str.lower()

#### Handling 'ship-state' column

In [36]:
newdf['ship-state']=newdf['ship-state'].str.lower().str.strip()

In [37]:
states_correction = {
    'pb': 'punjab',
    'rj': 'rajasthan',
    'nl': 'nagaland',
    'ar': 'arunachal pradesh',
    'apo': 'andhra pradesh',
    'rajshthan': 'rajasthan',
    'rajsthan': 'rajasthan',
    'new delhi': 'delhi',
    'punjab/mohali/zirakpur': 'punjab',
    'orissa': 'odisha',
    'pondicherry': 'puducherry',
    'andaman & nicobar': 'andaman & nicobar islands'
}

In [38]:
newdf['ship-state']=newdf['ship-state'].replace(states_correction)

In [39]:
newdf['ship-state']=newdf['ship-state'].str.title()

#### New address_df creation for future reference

In [40]:
address_df=newdf[['ship-city','ship-state','ship-postal-code']].copy()

#### 6. Creation of New Useful Columns from the existing ones

Creation of 'Month_Name' and 'Day_Name'

In [41]:
newdf['Month_Name']=newdf['Date'].dt.month_name()
newdf['Day_name']=newdf['Date'].dt.day_name()

#### Creation of Financial Quarter with year :

In [42]:
#Standard Quarter system maps Jan, Feb, Mar to Q1
newdf['Standard_Quarter'] = newdf['Date'].dt.quarter

#Mapping Apr, May, June to Q1 for the Indian Financial Year
newdf['Financial_Quarter'] = newdf['Date'].dt.month.map({
    4: 'Q1', 5: 'Q1', 6: 'Q1',
    7: 'Q2', 8: 'Q2', 9: 'Q2',
    10: 'Q3', 11: 'Q3', 12: 'Q3',
    1: 'Q4', 2: 'Q4', 3: 'Q4'
})

#Quarter Year : yyyy-Q# format
newdf['Quarter_Year'] = newdf['Date'].dt.year.astype(str) + '-' + newdf['Financial_Quarter']

newdf.drop(columns=['Standard_Quarter','Financial_Quarter'],inplace=True)

newdf['Quarter_Year'].head()

0    2022-Q1
1    2022-Q1
2    2022-Q1
3    2022-Q1
4    2022-Q1
Name: Quarter_Year, dtype: object

In [43]:
for col in newdf.columns:
    print(f"\n{col}:")
    print(newdf[col].unique())

Order ID:
['405-8078784-5731545' '171-9198151-1101146' '404-0687676-7273146' ...
 '407-9547469-3152358' '402-6184140-0545956' '408-7436540-8728312']

Date:
<DatetimeArray>
['2022-04-30 00:00:00', '2022-04-29 00:00:00', '2022-04-28 00:00:00',
 '2022-04-27 00:00:00', '2022-04-26 00:00:00', '2022-04-25 00:00:00',
 '2022-04-24 00:00:00', '2022-04-23 00:00:00', '2022-04-22 00:00:00',
 '2022-04-21 00:00:00', '2022-04-20 00:00:00', '2022-04-19 00:00:00',
 '2022-04-18 00:00:00', '2022-04-17 00:00:00', '2022-04-16 00:00:00',
 '2022-04-15 00:00:00', '2022-04-14 00:00:00', '2022-04-13 00:00:00',
 '2022-04-12 00:00:00', '2022-04-11 00:00:00', '2022-04-10 00:00:00',
 '2022-04-09 00:00:00', '2022-04-08 00:00:00', '2022-04-07 00:00:00',
 '2022-04-06 00:00:00', '2022-04-05 00:00:00', '2022-04-04 00:00:00',
 '2022-04-03 00:00:00', '2022-04-02 00:00:00', '2022-04-01 00:00:00',
 '2022-03-31 00:00:00', '2022-05-31 00:00:00', '2022-05-30 00:00:00',
 '2022-05-29 00:00:00', '2022-05-28 00:00:00', '2022-05-27 00:00:00',
 '2022-05-26 00:00:00', '2022-05-25 00:00:00', '2022-05-24 00:00:00',
 '2022-05-23 00:00:00', '2022-05-22 00:00:00', '2022-05-21 00:00:00',
 '2022-05-20 00:00:00', '2022-05-19 00:00:00', '2022-05-18 00:00:00',
 '2022-05-17 00:00:00', '2022-05-16 00:00:00', '2022-05-15 00:00:00',
 '2022-05-14 00:00:00', '2022-05-13 00:00:00', '2022-05-12 00:00:00',
 '2022-05-11 00:00:00', '2022-05-10 00:00:00', '2022-05-09 00:00:00',
 '2022-05-08 00:00:00', '2022-05-07 00:00:00', '2022-05-06 00:00:00',
 '2022-05-05 00:00:00', '2022-05-04 00:00:00', '2022-05-03 00:00:00',
 '2022-05-02 00:00:00', '2022-05-01 00:00:00', '2022-06-29 00:00:00',
 '2022-06-28 00:00:00', '2022-06-27 00:00:00', '2022-06-26 00:00:00',
 '2022-06-25 00:00:00', '2022-06-24 00:00:00', '2022-06-23 00:00:00',
 '2022-06-22 00:00:00', '2022-06-21 00:00:00', '2022-06-20 00:00:00',
 '2022-06-19 00:00:00', '2022-06-18 00:00:00', '2022-06-17 00:00:00',
 '2022-06-16 00:00:00', '2022-06-15 00:00:00', '2022-06-14 00:00:00',
 '2022-06-13 00:00:00', '2022-06-12 00:00:00', '2022-06-11 00:00:00',
 '2022-06-10 00:00:00', '2022-06-09 00:00:00', '2022-06-08 00:00:00',
 '2022-06-07 00:00:00', '2022-06-06 00:00:00', '2022-06-05 00:00:00',
 '2022-06-04 00:00:00', '2022-06-03 00:00:00', '2022-06-02 00:00:00',
 '2022-06-01 00:00:00']
Length: 91, dtype: datetime64[ns]

Status:
['Cancelled' 'Shipped - Delivered to Buyer' 'Shipped'
 'Shipped - Returned to Seller' 'Shipped - Rejected by Buyer'
 'Shipped - Lost in Transit' 'Shipped - Out for Delivery'
 'Shipped - Returning to Seller' 'Shipped - Picked Up' 'Pending'
 'Pending - Waiting for Pick Up' 'Shipped - Damaged' 'Shipping']

Fulfilment:
['merchant' 'amazon']

Sales Channel :
['amazon.in' 'non-amazon']

ship-service-level:
['standard' 'expedited']

Style:
['SET389' 'JNE3781' 'JNE3371' ... 'SET066' 'J0286' 'SET045']

SKU:
['SET389-KR-NP-S' 'JNE3781-KR-XXXL' 'JNE3371-KR-XL' ... 'JNE3370-KR-S'
 'JNE3678-TU-XXL' 'SET045-KR-NP-M']

Category:
['set' 'kurta' 'western' 'top' 'ethnic' 'bottom' 'saree' 'blouse'
 'dupatta']

Size:
['S' '3XL' 'XL' 'L' 'XXL' 'XS' '6XL' 'M' '4XL' '5XL' 'Free']

ASIN:
['B09KXVBD7Z' 'B09K3WFS32' 'B07WV4JV4D' ... 'B081X6MVKK' 'B0943HSR64'
 'B07N81TFNY']

Courier Status:
['cancelled' 'shipped' 'unshipped']

Qty:
[ 0  1  2 15  3  9 13  5  4  8]

Amount:
[ 647.62  406.    329.   ...  708.58 1244.    639.  ]

ship-city:
['MUMBAI' 'BENGALURU' 'NAVI MUMBAI' ... 'GULABPURA, Distt BHILWARA'
 'Prayagraj (ALLAHABAD)' 'Halol']

ship-state:
['Maharashtra' 'Karnataka' 'Puducherry' 'Tamil Nadu' 'Uttar Pradesh'
 'Chandigarh' 'Telangana' 'Andhra Pradesh' 'Rajasthan' 'Delhi' 'Haryana'
 'Assam' 'Jharkhand' 'Chhattisgarh' 'Odisha' 'Kerala' 'Madhya Pradesh'
 'West Bengal' 'Nagaland' 'Gujarat' 'Uttarakhand' 'Bihar'
 'Jammu & Kashmir' 'Punjab' 'Himachal Pradesh' 'Arunachal Pradesh'
 'Manipur' 'Goa' 'Meghalaya' 'Tripura' 'Ladakh' 'Dadra And Nagar' 'Sikkim'
 nan 'Andaman & Nicobar Islands' 'Mizoram' 'Lakshadweep']

ship-postal-code:
[400081. 560085. 410210. ... 609603. 851205. 629152.]

B2B:
[False  True]

Month_Name:
['April' 'March' 'May' 'June']

Day_name:
['Saturday' 'Friday' 'Thursday' 'Wednesday' 'Tuesday' 'Monday' 'Sunday']

Quarter_Year:
['2022-Q1' '2022-Q4']

#### Checking if the 'Amount' column is equal to the unit price of the product.

In [44]:
newdf['Revenue']=newdf['Qty']*newdf['Amount']
newdf['Check_Diff']=newdf['Revenue']-newdf['Amount']

In [45]:
newdf['Check_Diff'].unique()

array([ -647.62,     0.  ,  -753.33,  -570.48, -1105.36,  -463.81,
       -1249.11, -1058.93, -1278.57,  2130.  ,  -995.54, -1902.86,
        -473.33,  -344.76,  -734.29,  -437.14,  -386.67,  -452.38,
        2224.  ,  -358.1 ,  -700.96,  -280.95,  -493.33,  -469.52,
        -659.05,  -981.25,  -399.05,  -951.43,  1518.  ,  -722.86,
        -491.43,  -300.95,  -266.67,  -690.48,  -536.19,  -393.33,
        -872.38,  -350.48,  -540.95,  -277.14,  -313.33,  -750.48,
       -1143.75,  -785.71,  -785.72,  -380.  ,  1308.  ,  -856.2 ,
        -411.43,  -845.71,  -894.29,  -627.62,  -621.9 ,  -884.76,
        2256.  ,  -514.29,   972.  ,   864.  ,  -345.71,  -368.58,
        -554.29,  -768.57, -1047.32,  -492.38,   990.  ,  -922.32,
        -436.19,  -336.19,  -622.86,  -662.86,  -604.76,  -460.95,
        -686.67,  -346.67,  -448.57,  -451.43,  4350.  ,  -715.24,
        -842.86,  -595.24,  -630.48,  -708.57,  -522.86,  -403.81,
        -438.1 ,  -521.9 ,  -596.19,  -922.86,  -493.34,  -568.57,
        -818.1 ,  -633.33,  -652.38,  -427.62,  -325.71,  -246.67,
        -340.  ,  -508.57, -1194.64,  -784.76,  -540.96,  -878.1 ,
        -454.29, -1090.18,  -302.86,  -420.96,  -657.14,  -921.9 ,
         720.  ,  -605.71,  -475.24,  -494.29,  -440.  ,  -651.43,
        -625.71,  -600.95, -1159.82,  -680.95,  -519.05,  -815.24,
        -856.19,  -634.29,  -342.86,  -582.86,  -440.95, -1198.1 ,
        -599.05,   752.  ,  -992.86,  -686.66,   950.  ,  -270.48,
        1776.  ,  -408.57,  -328.57,   916.  ,  -362.86,  -701.9 ,
        -682.86, -1306.25,  -294.29,  -927.62, -1083.04,  -793.33,
        -460.96, -1121.43,  -474.11,  1398.  ,   974.  ,  -313.34,
        -471.43,  -551.43,  -536.2 ,  -811.43,  -296.19,  -560.  ,
        -543.81,  -420.95,  -535.24,  -832.38,  -424.76,  -920.95,
         884.  ,  -472.38,  -540.  ,   518.  ,  -496.19,  -950.89,
        -546.67,  1450.  ,  -539.05,  -520.54,  -628.57,   870.  ,
        1080.  , 21980.  ,   658.  ,   774.  ,  1296.  ,  -453.33,
        1194.  ,  -500.95,  -734.28,  -795.24, -1005.36,  -681.9 ,
         838.  ,  -284.76,  -562.86,   798.  ,  -463.8 ,  2198.  ,
        -700.95,  1238.  ,  -303.81,   942.  ,  -269.52, -1149.11,
        1576.  ,  -601.9 ,  -762.86,  -583.81,  -487.62,  3948.  ,
        -361.9 ,  -628.58,  -617.14,  -804.76,  -502.68,  1088.  ,
        -322.86,  1488.  ,  -369.52,  2652.  ,  1036.  ,   906.  ,
        -462.86,  -335.24, -1471.43,  -770.48,  1148.  ,  4464.  ,
        -533.33,  -359.05,  -357.14,  -839.04,  -721.9 ,   986.  ,
        -421.9 , -1038.4 ,  -368.57, -1268.58, -1325.72,  -455.24,
        -558.1 ,  -237.14,  -551.42,  -507.62,  -806.67,  -402.86,
        1136.  ,  -568.58,  2208.  ,  -394.29, -1025.89,  -414.29,
       -4235.72,  -300.96,  -359.04, -1011.61, -1359.82,  -874.28,
        -317.14,  -904.76, -1389.29,  -634.28,  -865.71,   724.  ,
        -583.04,  -433.33,  1798.  ,  -450.48,  1034.  ,  -518.1 ,
        2864.  ,  -448.58,  2230.  ,  -436.2 ,  -524.76,  -519.04,
       -1513.39,  1330.  ,  1934.  ,   848.  ,  -377.14,   736.  ,
         918.  ,  1648.  ,   568.  ,  1022.  , -1100.89,  3102.  ,
        2916.  ,  6204.  ,  1392.  ,  -404.76,  1320.  ,  4080.  ,
       -1266.66,  -413.33,   636.  ,  -449.52, -1033.93,  1990.  ,
        -453.34,  -665.71,  -651.42,   846.  ,   812.  ,  -370.48,
        1262.  ,  3786.  ,  1974.  ,  -680.96,  -868.57,  -560.95,
        -694.29,  -372.38,  -341.9 ,  -529.52,  -615.24,  8580.  ,
        1430.  ,  -753.34,  -501.9 ,   582.  ,  -430.48,  -855.24,
       -1008.04,  -588.57,  -865.18,  -650.48,  -364.76,  -374.29,
        1292.  ,  -947.62,  -471.42,  -314.29,  -321.9 ,  -416.19,
       39088.  ,  -360.95,  -279.05,  -458.1 ,  -306.67,  -597.14,
        -738.1 ,  -695.24,  -713.33,  -301.9 , -1329.52,  -760.95,
         560.  ,  -340.95, -1089.29, -1044.64,   852.  ,  1916.  ,
        -655.24,  -457.14,  1236.  ,  -236.19,  -251.43,   834.  ,
        -446.67,  -724.76,  -405.71,   900.  ,  -835.24,  -520.95,
       -1000.  ,   698.  ,  -664.76,  -431.43,  -823.81,  -347.62,
        1098.  ,  -950.48,  -400.  ,  -644.76,  2066.  , -1070.54,
        4032.  , -1111.61,  4794.  ,  -278.1 , -1182.14,  -611.43,
        -757.14,  -305.71, -1008.93,  1396.  , -1072.32,  -504.76,
        -565.71,  2034.  ,  2232.  ,  -772.38,  -880.95,  1282.  ,
        3846.  ,  -286.67,  -796.19,  -338.1 ,  -754.29,  -660.  ,
       -1338.39,  1542.  ,  -827.62,  -307.62,  -635.24,  1418.  ,
        -740.  ,  2298.  ,  1026.  ,  -903.81,  -292.38,  1332.  ,
        -599.04,  -511.43,  -503.81,  -367.62,  -332.38,  -385.71,
        -602.86,   764.  ,  1158.  ,  -327.62,  -745.71,  -680.  ,
        -747.62,  -339.05,  -574.29,  -520.  ,  1672.  ,  -351.43,
        -675.24,  5310.  ,  1770.  ,  -938.1 ,  -349.52,  2372.  ,
        -940.95,  -846.67,  -363.81,  -623.81,  3444.  ,  -791.07,
        -809.52,  -329.52,  -371.43,  -559.05,   602.  ,  -481.25,
        -764.76,  -612.38,  -464.76,  -626.67, -1010.71,  1554.  ,
        -538.1 ,  -629.52,  1228.  , -1285.72,  -792.38,  -573.34,
        -497.14,  -488.57,  -806.66,  1998.  ,  -498.1 , -1204.46,
       -1140.96,  -951.42,  1528.  ,  -576.19,  -919.05, -1104.46,
        2698.  ,   746.  , -1058.92,  -953.57,  -775.24,  -610.48,
       -1028.57,  -949.11,  -547.62,  -978.57,  -420.  , -1283.93,
       -1350.48,  -337.14,  -836.19,  -760.  ,  -692.38,  -300.  ,
        1714.  ,  -486.67,  -355.24,  -665.72,  -584.76,  -353.33,
        -642.86,  1582.  ,  -941.9 , -1222.32,  -561.9 ,  -685.72,
       -1028.58,  -542.86,  -513.33,  -511.42,  1250.  ,  -748.57,
        -315.24, -1216.07,  -600.  ,  1708.  ,  -517.14,  -308.57,
        1310.  ,  -411.42,  -797.14,  -816.19,  -822.86,  1198.  ,
        -839.05,  -957.14, -1001.79,  1132.  ,  4116.  ,  1372.  ,
        2676.  ,  1224.  ,  3672.  ,  -363.8 ,  -727.6 ,  -986.67,
       -1177.68, -1190.18,  -410.48, -1004.46, -1287.5 ,  -959.82,
        -378.1 ,  -482.86,  2496.  ,   832.  ,  -788.57,  -960.  ,
        -577.14,  -700.  ,  -409.52,  -527.62,  -592.38,  -838.1 ,
        -932.38,  -714.29,  -912.38,  -814.29,  -980.36,  -840.  ,
       -1048.21,  -567.62,  -523.8 ,  1404.  ,  -971.43,  -319.05,
        -401.9 ,  -365.71,  -553.33, -1174.11,  -474.29,  -578.1 ,
        -477.14,  -805.71,   584.  ,  1226.  ,  -632.38,  3144.  ,
        8388.  ,  3528.  ,  3594.  , -1248.21,   836.  , -1039.29,
        -526.67,  -499.05,   998.  , -1097.32,  -566.67,  -707.62,
        1650.  , -1122.32,  -689.52,  -295.24, -1023.21, -1075.89,
        -603.81,  -403.8 ,  -777.14,  1190.  ,  1486.  ,  -441.9 ,
       -2259.99,  1268.  ,  -852.38, -1006.25,  -975.89,  9108.  ,
        1448.  ,  2292.  ,  -218.1 , -1468.58,  -811.42,  -541.9 ,
        1386.  ,  -994.29,  -396.19,  -727.62,   952.  ,  1470.  ,
       -1039.05,  1270.  ,  -908.93,  2326.  , -1038.39, -1115.18,
        -677.14,  1598.  ,  -760.96, -1315.18,  -467.62,  -726.67,
        1498.  ,   982.  ,  1074.  ,  -691.43, -2389.28,  -531.43,
        -309.52,  -718.1 ,  -656.19,  -633.34,   706.  ,  -415.24,
        1130.  ,  -445.71, -1239.29,  -485.72,  -837.14,  -485.71,
       -1431.25,  -830.48, -1123.21,  -293.33,  -398.1 ,  -645.71,
       -1112.38,  -778.1 ,   992.  , -1158.04,  1662.  ,  -969.52,
        -668.57,  -739.04,   936.  ,  -993.33, -1130.48,  1014.  ,
        -366.67,  -435.24,  -619.05,  -683.81,  1176.  , -1064.29,
        -981.9 ,  1584.  ,  -940.  , -1050.  ,  -723.81,  1328.  ,
        -902.86,  -331.43,  1138.  ,  -386.66,  1976.  ,  1290.  ,
         886.  ,  -500.  ,  -596.2 ,  -417.14,  -920.54, -1134.82,
        -466.67,  -286.66,  1752.  , -1161.61,  2250.  ,  5220.  ,
        8700.  ,  1384.  , -1232.38,  -976.79,  -456.19,  1516.  ,
       -1059.82,  1376.  ,  -614.29,  -752.38,  -989.52,   914.  ,
       -1042.86, -2319.64,  2016.  ,  2182.  ,  1472.  ,  1458.  ,
        -569.52,  -545.72,   666.  ,  -694.28, -1025.  ,   690.  ,
        3408.  ,  2754.  ,  7992.  ,  2894.  ,  1124.  ,  -631.43,
        -544.76,  -639.05,  1574.  ,  -932.14,  2244.  ,  2322.  ,
        4512.  ,  -444.76,  -523.81,  -796.2 ,  -502.86,  -505.71,
        -736.19,  -545.71,  -574.11,  -719.05,  -829.52,  -708.58,
        1244.  ])

#### Bulk Buys in the list, where the difference between the Revenue and the Amount is more than 5000

In [46]:
bulk_orders = newdf[newdf['Check_Diff'] > 5000]
print(bulk_orders[['Order ID', 'Category', 'Qty', 'Amount', 'Revenue']])

                   Order ID Category  Qty  Amount  Revenue
11160   403-4106553-1691525      set    5  5495.0  27475.0
33333   405-4755854-9568304    kurta    4  2068.0   8272.0
39944   408-3363121-6123562  western    4  2860.0  11440.0
42039   402-5239558-4281957      set    8  5584.0  44672.0
54605   171-9419863-7830701  western    3  2655.0   7965.0
79899   405-6877720-7865168    kurta    4  2796.0  11184.0
89150   406-7195963-2374765      set    4  3036.0  12144.0
113339  403-1620002-1689968    kurta    4  1740.0   6960.0
113350  403-4040971-3884354    kurta    5  2175.0  10875.0
121019  403-0343365-3075550      set    4  2664.0  10656.0

#### Fixing the Revenue Logic :<br> 
#### As we saw that "Amount" is basically unit product price : we will rename the column into "Unit Price"

In [47]:
newdf.rename(columns={'Amount':'Unit_Price'},inplace=True)

#### We create final revenue column : 'Total_Revenue'

In [48]:
newdf['Total_Revenue']=newdf['Qty']*newdf['Unit_Price']

#### Drop the unnecessary columns :

In [49]:
newdf.drop(columns=['Revenue','Check_Diff'],inplace=True)

In [50]:
newdf.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'Unit_Price', 'ship-city', 'ship-state',
       'ship-postal-code', 'B2B', 'Month_Name', 'Day_name', 'Quarter_Year',
       'Total_Revenue'],
      dtype='object')

## Creation of cleaned dataset

In [52]:
newdf.to_csv('cleaned_data.csv',index=False)
address_df.to_csv('address_data.csv')