## Week 1: Data Understanding & Preprocessing
### Task 1 : Setup & GitHub Integration

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Dataset/Amazon Sale Report.csv')
df.head() #default it will show us 5 rows
#we can also do df.head(any num) to show the particular number of rows.

/var/folders/n6/rdkdg7zn25j638bgsp4jznjc0000gp/T/ipykernel_14317/1713099920.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Dataset/Amazon Sale Report.csv')

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

## Task 2 : Data Cleaning & Preprocessing

#### 1. Basic Description of the dataset

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

#### 2a. Identify and Display in every column how many Missing Values are present

In [4]:
df.isnull().any()

index                 False
Order ID              False
Date                  False
Status                False
Fulfilment            False
Sales Channel         False
ship-service-level    False
Style                 False
SKU                   False
Category              False
Size                  False
ASIN                  False
Courier Status         True
Qty                   False
currency               True
Amount                 True
ship-city              True
ship-state             True
ship-postal-code       True
ship-country           True
promotion-ids          True
B2B                   False
fulfilled-by           True
Unnamed: 22            True
dtype: bool

In [5]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

#### 2b. Check for duplicate rows and Count them

In [6]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
128970    False
128971    False
128972    False
128973    False
128974    False
Length: 128975, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [index, Order ID, Date, Status, Fulfilment, Sales Channel , ship-service-level, Style, SKU, Category, Size, ASIN, Courier Status, Qty, currency, Amount, ship-city, ship-state, ship-postal-code, ship-country, promotion-ids, B2B, fulfilled-by, Unnamed: 22]
Index: []

[0 rows x 24 columns]

#### 2c. Finding the inconsistencies :

In [9]:
for col in df.columns:
    print(col)

index
Order ID
Date
Status
Fulfilment
Sales Channel
ship-service-level
Style
SKU
Category
Size
ASIN
Courier Status
Qty
currency
Amount
ship-city
ship-state
ship-postal-code
ship-country
promotion-ids
B2B
fulfilled-by
Unnamed: 22

In [10]:
for col in df.columns:
    print(f"\n{col}:")
    print(df[col].unique())

index:
[     0      1      2 ... 128972 128973 128974]

Order ID:
['405-8078784-5731545' '171-9198151-1101146' '404-0687676-7273146' ...
 '407-9547469-3152358' '402-6184140-0545956' '408-7436540-8728312']

Date:
['04-30-22' '04-29-22' '04-28-22' '04-27-22' '04-26-22' '04-25-22'
 '04-24-22' '04-23-22' '04-22-22' '04-21-22' '04-20-22' '04-19-22'
 '04-18-22' '04-17-22' '04-16-22' '04-15-22' '04-14-22' '04-13-22'
 '04-12-22' '04-11-22' '04-10-22' '04-09-22' '04-08-22' '04-07-22'
 '04-06-22' '04-05-22' '04-04-22' '04-03-22' '04-02-22' '04-01-22'
 '03-31-22' '05-31-22' '05-30-22' '05-29-22' '05-28-22' '05-27-22'
 '05-26-22' '05-25-22' '05-24-22' '05-23-22' '05-22-22' '05-21-22'
 '05-20-22' '05-19-22' '05-18-22' '05-17-22' '05-16-22' '05-15-22'
 '05-14-22' '05-13-22' '05-12-22' '05-11-22' '05-10-22' '05-09-22'
 '05-08-22' '05-07-22' '05-06-22' '05-05-22' '05-04-22' '05-03-22'
 '05-02-22' '05-01-22' '06-29-22' '06-28-22' '06-27-22' '06-26-22'
 '06-25-22' '06-24-22' '06-23-22' '06-22-22' '06-21-22' '06-20-22'
 '06-19-22' '06-18-22' '06-17-22' '06-16-22' '06-15-22' '06-14-22'
 '06-13-22' '06-12-22' '06-11-22' '06-10-22' '06-09-22' '06-08-22'
 '06-07-22' '06-06-22' '06-05-22' '06-04-22' '06-03-22' '06-02-22'
 '06-01-22']

Status:
['Cancelled' 'Shipped - Delivered to Buyer' 'Shipped'
 'Shipped - Returned to Seller' 'Shipped - Rejected by Buyer'
 'Shipped - Lost in Transit' 'Shipped - Out for Delivery'
 'Shipped - Returning to Seller' 'Shipped - Picked Up' 'Pending'
 'Pending - Waiting for Pick Up' 'Shipped - Damaged' 'Shipping']

Fulfilment:
['Merchant' 'Amazon']

Sales Channel :
['Amazon.in' 'Non-Amazon']

ship-service-level:
['Standard' 'Expedited']

Style:
['SET389' 'JNE3781' 'JNE3371' ... 'SET066' 'J0286' 'SET045']

SKU:
['SET389-KR-NP-S' 'JNE3781-KR-XXXL' 'JNE3371-KR-XL' ... 'JNE3370-KR-S'
 'JNE3678-TU-XXL' 'SET045-KR-NP-M']

Category:
['Set' 'kurta' 'Western Dress' 'Top' 'Ethnic Dress' 'Bottom' 'Saree'
 'Blouse' 'Dupatta']

Size:
['S' '3XL' 'XL' 'L' 'XXL' 'XS' '6XL' 'M' '4XL' '5XL' 'Free']

ASIN:
['B09KXVBD7Z' 'B09K3WFS32' 'B07WV4JV4D' ... 'B081X6MVKK' 'B0943HSR64'
 'B07N81TFNY']

Courier Status:
[nan 'Shipped' 'Cancelled' 'Unshipped']

Qty:
[ 0  1  2 15  3  9 13  5  4  8]

currency:
['INR' nan]

Amount:
[ 647.62  406.    329.   ...  708.58 1244.    639.  ]

ship-city:
['MUMBAI' 'BENGALURU' 'NAVI MUMBAI' ... 'GULABPURA, Distt BHILWARA'
 'Prayagraj (ALLAHABAD)' 'Halol']

ship-state:
['MAHARASHTRA' 'KARNATAKA' 'PUDUCHERRY' 'TAMIL NADU' 'UTTAR PRADESH'
 'CHANDIGARH' 'TELANGANA' 'ANDHRA PRADESH' 'RAJASTHAN' 'DELHI' 'HARYANA'
 'ASSAM' 'JHARKHAND' 'CHHATTISGARH' 'ODISHA' 'KERALA' 'MADHYA PRADESH'
 'WEST BENGAL' 'NAGALAND' 'Gujarat' 'UTTARAKHAND' 'BIHAR'
 'JAMMU & KASHMIR' 'PUNJAB' 'HIMACHAL PRADESH' 'ARUNACHAL PRADESH'
 'MANIPUR' 'Goa' 'MEGHALAYA' 'GOA' 'TRIPURA' 'LADAKH' 'DADRA AND NAGAR'
 'SIKKIM' 'Delhi' nan 'ANDAMAN & NICOBAR ' 'Punjab' 'Rajshthan' 'Manipur'
 'rajasthan' 'Odisha' 'NL' 'Bihar' 'MIZORAM' 'punjab' 'New Delhi'
 'Rajasthan' 'Punjab/Mohali/Zirakpur' 'Puducherry' 'delhi' 'RJ'
 'Chandigarh' 'orissa' 'LAKSHADWEEP' 'goa' 'PB' 'APO' 'Arunachal Pradesh'
 'AR' 'Pondicherry' 'Sikkim' 'Arunachal pradesh' 'Nagaland' 'bihar'
 'Mizoram' 'rajsthan' 'Orissa' 'Rajsthan' 'Meghalaya']

ship-postal-code:
[400081. 560085. 410210. ... 609603. 851205. 629152.]

ship-country:
['IN' nan]

promotion-ids:
[nan
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-CXNSLNBROFDW4,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-WSJLDN3X7KEMO,Amazon PLCC Free-Financing Universal Merchant AAT-VL6FGQVGQVXUS,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-XVPICCHRWDCAI,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'IN Core Free Shipping 2015/04/08 23-48-5-108' ...
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4'
 'Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292']

B2B:
[False  True]

fulfilled-by:
['Easy Ship' nan]

Unnamed: 22:
[nan False]

In [11]:
# Inconsistency in the state names :
df['ship-state'].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'Gujarat', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'Goa', 'MEGHALAYA', 'GOA',
       'TRIPURA', 'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'Delhi', nan,
       'ANDAMAN & NICOBAR ', 'Punjab', 'Rajshthan', 'Manipur',
       'rajasthan', 'Odisha', 'NL', 'Bihar', 'MIZORAM', 'punjab',
       'New Delhi', 'Rajasthan', 'Punjab/Mohali/Zirakpur', 'Puducherry',
       'delhi', 'RJ', 'Chandigarh', 'orissa', 'LAKSHADWEEP', 'goa', 'PB',
       'APO', 'Arunachal Pradesh', 'AR', 'Pondicherry', 'Sikkim',
       'Arunachal pradesh', 'Nagaland', 'bihar', 'Mizoram', 'rajsthan',
       'Orissa', 'Rajsthan', 'Meghalaya'], dtype=object)

In [12]:
df['ship-state'].str.lower().value_counts()

ship-state
maharashtra               22260
karnataka                 17326
tamil nadu                11483
telangana                 11330
uttar pradesh             10638
delhi                      6967
kerala                     6585
west bengal                5963
andhra pradesh             5430
gujarat                    4489
haryana                    4415
rajasthan                  2711
madhya pradesh             2529
odisha                     2136
bihar                      2114
punjab                     1917
assam                      1663
uttarakhand                1553
jharkhand                  1456
goa                        1137
chhattisgarh                909
himachal pradesh            788
jammu & kashmir             702
puducherry                  350
chandigarh                  333
manipur                     316
andaman & nicobar           257
meghalaya                   207
sikkim                      205
nagaland                    185
tripura                     151
arunachal pradesh           146
new delhi                    81
mizoram                      76
dadra and nagar              70
ladakh                       43
lakshadweep                   4
rajshthan                     3
orissa                        3
nl                            2
rj                            2
rajsthan                      2
punjab/mohali/zirakpur        1
pb                            1
apo                           1
ar                            1
pondicherry                   1
Name: count, dtype: int64

In [13]:
df['ship-city'].str.lower().value_counts()

ship-city
bengaluru                11898
hyderabad                 9125
mumbai                    7122
new delhi                 6340
chennai                   6284
                         ...
kim                          1
edapally north po            1
mandi gobindgarh             1
cherupuzha                   1
prayagraj (allahabad)        1
Name: count, Length: 7297, dtype: int64

#### state-name column inconsistencies : 
1. Names of state are repeated (lowercase, uppercase).
2. After making every names into lowercase and finding the sum, we found that there are some state names given in the SHORTFORMS which again makes it inconsistent.

#### state-city column inconsistencies : 
1. Some entries have bracketed alternate names.

#### 3. Handling missing values :

#### 3a. Removal of unnecessary columns :

In [14]:
# 'Unnamed: 22', 'promotion-ids', 'fulfilled-by' columns are of no use, so they are being dropped.
newdf = df.drop(columns=['Unnamed: 22', 'fulfilled-by'])

#### 3b. Missing values checking :

In [15]:
(newdf.isna().mean() * 100).sort_values(ascending=False)

promotion-ids         38.110487
Amount                 6.043807
currency               6.043807
Courier Status         5.328164
ship-country           0.025586
ship-postal-code       0.025586
ship-state             0.025586
ship-city              0.025586
index                  0.000000
Order ID               0.000000
Qty                    0.000000
ASIN                   0.000000
Size                   0.000000
Category               0.000000
SKU                    0.000000
Style                  0.000000
ship-service-level     0.000000
Sales Channel          0.000000
Fulfilment             0.000000
Status                 0.000000
Date                   0.000000
B2B                    0.000000
dtype: float64

In [16]:
newdf[newdf['Amount'].isna()]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
29,29,404-5933402-8801952,04-30-22,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,...,NaN,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False
65,65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,...,Cancelled,0,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False
84,84,403-9950518-0349133,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,...,Cancelled,0,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,NaN,False
95,95,405-9112089-3379536,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,...,Cancelled,0,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128903,128903,406-3923120-4345139,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3801,JNE3801-KR-M,kurta,...,Cancelled,0,NaN,NaN,ANANTAPUR,ANDHRA PRADESH,515001.0,IN,NaN,False
128907,128907,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW014,NW014-ST-SR-XXXL,Set,...,Cancelled,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,NaN,False
128908,128908,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW007,NW007-ST-CP-XXXL,Set,...,Cancelled,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,NaN,False
128958,128958,408-9513596-4393945,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,SET058,SET058-KR-NP-L,Set,...,Cancelled,0,NaN,NaN,Bengaluru,KARNATAKA,560037.0,IN,NaN,False
128967,128967,404-5182288-1653947,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,...,Cancelled,0,NaN,NaN,Kolkata,WEST BENGAL,700040.0,IN,NaN,False

In [17]:
newdf['Amount']=df['Amount'].fillna(0.00)

In [18]:
newdf['currency']=df['currency'].fillna('INR')

In [19]:
(newdf.isna().mean() * 100).sort_values(ascending=False)

promotion-ids         38.110487
Courier Status         5.328164
ship-country           0.025586
ship-postal-code       0.025586
ship-state             0.025586
ship-city              0.025586
index                  0.000000
Order ID               0.000000
Amount                 0.000000
currency               0.000000
Qty                    0.000000
ASIN                   0.000000
Size                   0.000000
Category               0.000000
SKU                    0.000000
Style                  0.000000
ship-service-level     0.000000
Sales Channel          0.000000
Fulfilment             0.000000
Status                 0.000000
Date                   0.000000
B2B                    0.000000
dtype: float64

In [20]:
newdf=newdf.drop(columns=['index','ship-country'])

In [21]:
newdf['promotion-ids']=newdf['promotion-ids'].fillna('no')

In [25]:
newdf.loc[(newdf['Courier Status'].isna()) & (newdf['Status']=='Cancelled'),'Courier Status']='Cancelled'

In [26]:
newdf['Courier Status']=newdf['Courier Status'].fillna('Cancelled')

In [27]:
(newdf.isna().mean() * 100).sort_values(ascending=False)

ship-postal-code      0.025586
ship-state            0.025586
ship-city             0.025586
Order ID              0.000000
Date                  0.000000
promotion-ids         0.000000
Amount                0.000000
currency              0.000000
Qty                   0.000000
Courier Status        0.000000
ASIN                  0.000000
Size                  0.000000
Category              0.000000
SKU                   0.000000
Style                 0.000000
ship-service-level    0.000000
Sales Channel         0.000000
Fulfilment            0.000000
Status                0.000000
B2B                   0.000000
dtype: float64

#### 4. Converted date fields to proper datetime format.

In [22]:
df['Date'].dropna().unique()

array(['04-30-22', '04-29-22', '04-28-22', '04-27-22', '04-26-22',
       '04-25-22', '04-24-22', '04-23-22', '04-22-22', '04-21-22',
       '04-20-22', '04-19-22', '04-18-22', '04-17-22', '04-16-22',
       '04-15-22', '04-14-22', '04-13-22', '04-12-22', '04-11-22',
       '04-10-22', '04-09-22', '04-08-22', '04-07-22', '04-06-22',
       '04-05-22', '04-04-22', '04-03-22', '04-02-22', '04-01-22',
       '03-31-22', '05-31-22', '05-30-22', '05-29-22', '05-28-22',
       '05-27-22', '05-26-22', '05-25-22', '05-24-22', '05-23-22',
       '05-22-22', '05-21-22', '05-20-22', '05-19-22', '05-18-22',
       '05-17-22', '05-16-22', '05-15-22', '05-14-22', '05-13-22',
       '05-12-22', '05-11-22', '05-10-22', '05-09-22', '05-08-22',
       '05-07-22', '05-06-22', '05-05-22', '05-04-22', '05-03-22',
       '05-02-22', '05-01-22', '06-29-22', '06-28-22', '06-27-22',
       '06-26-22', '06-25-22', '06-24-22', '06-23-22', '06-22-22',
       '06-21-22', '06-20-22', '06-19-22', '06-18-22', '06-17-22',
       '06-16-22', '06-15-22', '06-14-22', '06-13-22', '06-12-22',
       '06-11-22', '06-10-22', '06-09-22', '06-08-22', '06-07-22',
       '06-06-22', '06-05-22', '06-04-22', '06-03-22', '06-02-22',
       '06-01-22'], dtype=object)

In [23]:
newdf['Date']=pd.to_datetime(df['Date'],format='%m-%d-%y',errors='coerce')

In [24]:
newdf['Date'].unique()

<DatetimeArray>
['2022-04-30 00:00:00', '2022-04-29 00:00:00', '2022-04-28 00:00:00',
 '2022-04-27 00:00:00', '2022-04-26 00:00:00', '2022-04-25 00:00:00',
 '2022-04-24 00:00:00', '2022-04-23 00:00:00', '2022-04-22 00:00:00',
 '2022-04-21 00:00:00', '2022-04-20 00:00:00', '2022-04-19 00:00:00',
 '2022-04-18 00:00:00', '2022-04-17 00:00:00', '2022-04-16 00:00:00',
 '2022-04-15 00:00:00', '2022-04-14 00:00:00', '2022-04-13 00:00:00',
 '2022-04-12 00:00:00', '2022-04-11 00:00:00', '2022-04-10 00:00:00',
 '2022-04-09 00:00:00', '2022-04-08 00:00:00', '2022-04-07 00:00:00',
 '2022-04-06 00:00:00', '2022-04-05 00:00:00', '2022-04-04 00:00:00',
 '2022-04-03 00:00:00', '2022-04-02 00:00:00', '2022-04-01 00:00:00',
 '2022-03-31 00:00:00', '2022-05-31 00:00:00', '2022-05-30 00:00:00',
 '2022-05-29 00:00:00', '2022-05-28 00:00:00', '2022-05-27 00:00:00',
 '2022-05-26 00:00:00', '2022-05-25 00:00:00', '2022-05-24 00:00:00',
 '2022-05-23 00:00:00', '2022-05-22 00:00:00', '2022-05-21 00:00:00',
 '2022-05-20 00:00:00', '2022-05-19 00:00:00', '2022-05-18 00:00:00',
 '2022-05-17 00:00:00', '2022-05-16 00:00:00', '2022-05-15 00:00:00',
 '2022-05-14 00:00:00', '2022-05-13 00:00:00', '2022-05-12 00:00:00',
 '2022-05-11 00:00:00', '2022-05-10 00:00:00', '2022-05-09 00:00:00',
 '2022-05-08 00:00:00', '2022-05-07 00:00:00', '2022-05-06 00:00:00',
 '2022-05-05 00:00:00', '2022-05-04 00:00:00', '2022-05-03 00:00:00',
 '2022-05-02 00:00:00', '2022-05-01 00:00:00', '2022-06-29 00:00:00',
 '2022-06-28 00:00:00', '2022-06-27 00:00:00', '2022-06-26 00:00:00',
 '2022-06-25 00:00:00', '2022-06-24 00:00:00', '2022-06-23 00:00:00',
 '2022-06-22 00:00:00', '2022-06-21 00:00:00', '2022-06-20 00:00:00',
 '2022-06-19 00:00:00', '2022-06-18 00:00:00', '2022-06-17 00:00:00',
 '2022-06-16 00:00:00', '2022-06-15 00:00:00', '2022-06-14 00:00:00',
 '2022-06-13 00:00:00', '2022-06-12 00:00:00', '2022-06-11 00:00:00',
 '2022-06-10 00:00:00', '2022-06-09 00:00:00', '2022-06-08 00:00:00',
 '2022-06-07 00:00:00', '2022-06-06 00:00:00', '2022-06-05 00:00:00',
 '2022-06-04 00:00:00', '2022-06-03 00:00:00', '2022-06-02 00:00:00',
 '2022-06-01 00:00:00']
Length: 91, dtype: datetime64[ns]